CREATE TABLE episodeIV (name STRING, line STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
LOAD DATA LOCAL INPATH 'root/inputs/episodeIV_dialouges.txt' INTO TABLE episodeIV;

INSERT OVERWRITE DIRECTORY '/user/chandra/output'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT name, COUNT(name) AS no_of_lines from episodeIV
GROUP BY name ORDER BY no_of_lines DESC;
dfs -get /user/chandra/output /root/output;
