show databases;

create database office;

use office;

CREATE TABLE employee
(id INT, name STRING, dept STRING, yoj INT, salary INT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
TBLPROPERTIES ("skip.header.line.count"="1");

DESCRIBE employee;

LOAD DATA LOCAL INPATH
'/root/EmpData.csv'
INTO TABLE employee;

INSERT OVERWRITE DIRECTORY '/user/chandra/textData/output/export'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT * FROM emp.employee;

SELECT COUNT(*) FROM employee;
